# Generated by Django 4.2.27 on 2026-01-26 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('character', 'Character'), ('location', 'Location'), ('event', 'Event'), ('item', 'Item'), ('concept', 'Concept'), ('note', 'Note')], default='note', max_length=50)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='nodes.node')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
