# Generated by Django 4.2.28 on 2026-02-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('character', 'Character'), ('location', 'Location'), ('event', 'Event'), ('item', 'Item'), ('concept', 'Concept'), ('note', 'Note'), ('frame', 'Frame')], default='note', max_length=50),
        ),
    ]
