# Generated by Django 4.2.28 on 2026-02-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_add_frame_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
