# Generated by Django 4.2.27 on 2026-01-26 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('graphs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='graphnode',
            constraint=models.UniqueConstraint(fields=('graph', 'node'), name='uniq_node_per_graph'),
        ),
        migrations.AddConstraint(
            model_name='graph',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_graph_name_per_project'),
        ),
    ]
