# Generated by Django 4.2.28 on 2026-02-25 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphnode',
            name='height',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='graphnode',
            name='is_frame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graphnode',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='graphs.graphnode'),
        ),
        migrations.AddField(
            model_name='graphnode',
            name='width',
            field=models.IntegerField(default=400),
        ),
    ]
