# Generated by Django 4.2.28 on 2026-03-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('forward', 'Forward (A → B)'), ('reverse', 'Reverse (B → A)'), ('bidirectional', 'Bidirectional (A ↔ B)'), ('undirected', 'Undirected (A — B)')], default='forward', max_length=15)),
                ('source_handle_position', models.FloatField(blank=True, default=None, null=True)),
                ('target_handle_position', models.FloatField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='connections.connectiontype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
