# Generated by Django 4.2.27 on 2026-01-26 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconnection',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='graphs.graph'),
        ),
    ]
