# Generated by Django 4.2.28 on 2026-03-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('connections', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_types', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeconnection',
            unique_together={('graph', 'source_node', 'target_node', 'connection_type')},
        ),
        migrations.AlterUniqueTogether(
            name='connectiontype',
            unique_together={('project', 'name')},
        ),
    ]
