# Generated by Django 4.2.28 on 2026-03-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconnection',
            name='direction',
            field=models.CharField(choices=[('forward', 'Forward (A → B)'), ('reverse', 'Reverse (B → A)'), ('bidirectional', 'Bidirectional (A ↔ B)'), ('undirected', 'Undirected (A — B)')], default='forward', max_length=15),
        ),
        migrations.AddField(
            model_name='nodeconnection',
            name='source_handle_position',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nodeconnection',
            name='target_handle_position',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
